services:
  db:
    container_name: wtpos_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5632:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: be.dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: fe.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    restart: always
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdata: {}