services:
  db:
    container_name: wtpos_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5632:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}