services:
  db:
    container_name: wtpos_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5632:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: be.dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:postgres@localhost:5632/postgres?schema=public
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5632/postgres?schema=public

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: fe.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - backend

volumes:
  pgdata: {}